# Autor: Steveen Carabalí
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmqA-compose
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    healthcheck: 
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - distribuidos-network

  categoria:
    image: acrsteveendev.azurecr.io/categoria:latest
    container_name: categoria-api-compose
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: >-
        Server=tcp:srv-steveen-dev.database.windows.net,1433;
        Database=db-tarea-microservicios;
        User Id=steveenadmin;
        Password=@Tequieromucho01;
        Encrypt=True;
        TrustServerCertificate=False;
        Connection Timeout=30;
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: admin
      RabbitMQ__Password: 123456
      RabbitMQ__QueueName: categoria_creada
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - distribuidos-network

  vehiculo:
    image: acrsteveendev.azurecr.io/vehiculo:latest
    container_name: vehiculo-api-compose
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__VehiculoConnection: >-
        Server=tcp:srv-steveen-dev.database.windows.net,1433;
        Database=db-tarea-microservicios;
        User Id=steveenadmin;
        Password=@Tequieromucho01;
        Encrypt=True;
        TrustServerCertificate=False;
        Connection Timeout=30;
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: admin
      RabbitMQ__Password: 123456
      RabbitMQ__QueueName: categoria_creada
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - distribuidos-network

  oauthjwt:
    image: acrsteveendev.azurecr.io/oauthjwt:latest
    container_name: oauthjwt-api-compose
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
    networks:
      - distribuidos-network

  apigateway:
    image: acrsteveendev.azurecr.io/apigateway:latest
    container_name: apigateway-api-compose
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      
      # REGLAS DE CATEGORÍA
      ReverseProxy__Routes__categoriasRoute__ClusterId: "categoriasCluster"
      ReverseProxy__Routes__categoriasRoute__Match__Path: "/api/Categoria/{**catch-all}"
      ReverseProxy__Clusters__categoriasCluster__Destinations__categoriasDestination__Address: "http://categoria:8080"
      
      # REGLAS DE VEHÍCULO
      ReverseProxy__Routes__vehiculosRoute__ClusterId: "vehiculosCluster"
      ReverseProxy__Routes__vehiculosRoute__Match__Path: "/api/Vehiculo/{**catch-all}"
      ReverseProxy__Clusters__vehiculosCluster__Destinations__vehiculosDestination__Address: "http://vehiculo:8080"
      
      # REGLAS DE SEGURIDAD OAUTHJWT
      ReverseProxy__Routes__authRoute__ClusterId: "authCluster"
      ReverseProxy__Routes__authRoute__Match__Path: "/api/Auth/{**catch-all}"
      ReverseProxy__Clusters__authCluster__Destinations__authDestination__Address: "http://oauthjwt:8080"
      
    depends_on: 
      - categoria
      - vehiculo
      - oauthjwt
    networks:
      - distribuidos-network

networks:
  distribuidos-network:
    driver: bridge